version: "3.8"

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: fampay_assignment
      MYSQL_USER: admin
      MYSQL_PASSWORD: fampay
      MYSQL_ROOT_PASSWORD: fampay
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $HTTP_PORT:$HTTP_PORT
    stdin_open: true
    tty: true

networks:
  internalnet:
    driver: bridge
